# Generated by Django 5.0.6 on 2024-07-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task',
            new_name='tasklist',
        ),
    ]
